#!/usr/bin/env bash
# install and config nginx in my server

apt update
apt install -y nginx
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
        
	root /var/www/html;
	index index.html;
	
	# redirection config
	#here_redirect_config
	
	# not found page 404
	#here_404_not_found_page_config
	}" > /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
