#!/usr/bin/env bash
#config a new server and  permanat redirection

apt update
apt install -y nginx
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	# redirection config
	#here_redirect_config

	# not found page 404
	#here_404_not_found_page_config
	}" > /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.html
old_str="#here_redirect_config"
redirect_path="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s|$old_str|$redirect_path|" /etc/nginx/sites-available/default
service nginx restart
