#!/usr/bin/env bash
# Config nginx so that it runs as nginx user and listen to  all active IPs ports
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sudo sed -i '21s/.*/\tlisten 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i '22s/.*/\tlisten [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
